name: Promote Python Package

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version to promote (e.g., 0.0.1)'
        required: true

env:
  CLOUDSMITH_NAMESPACE: interview-shubh-pandey
  CLOUDSMITH_STAGING_REPO: staging
  CLOUDSMITH_PRODUCTION_REPO: production

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install Cloudsmith CLI
        run: pip install cloudsmith-cli

      - name: Authenticate Cloudsmith
        run: cloudsmith login --api-key ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Tag and promote package to production
        run: |
          PACKAGE_VERSION="${{ github.event.inputs.package_version }}"
          echo "Received input to promote version: $PACKAGE_VERSION"
          
          echo "Fetching package metadata from Cloudsmith..."
          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -q "version:$PACKAGE_VERSION" -F json)

          IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')

          if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" == "null" ]; then
            echo "No package found with version: $PACKAGE_VERSION"
            exit 1
          fi

          echo "Tagging package $IDENTIFIER with 'ready-for-production'..."
          cloudsmith tag add ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER ready-for-production

          echo "Promoting package $IDENTIFIER to production..."
          cloudsmith mv --yes ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
