name: Promote Python Package

on:
  repository_dispatch:
    types: [cloudsmith-promote]

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

permissions:
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Promote tagged packages
        run: |
          echo "Looking for packages tagged with ready-for-production..."
          PACKAGE_DATA=$(cloudsmith list package $CLOUDSMITH_NAMESPACE/$CLOUDSMITH_STAGING_REPO -q "tag:ready-for-production" -F json)

          COUNT=$(echo "$PACKAGE_DATA" | jq '.data | length')
          if [ "$COUNT" -eq 0 ]; then
            echo "No packages tagged as ready-for-production found"
            exit 0
          fi

          for IDENTIFIER in $(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm'); do
            echo "Promoting $IDENTIFIER to production..."
            cloudsmith mv --yes \
              $CLOUDSMITH_NAMESPACE/$CLOUDSMITH_STAGING_REPO/$IDENTIFIER \
              $CLOUDSMITH_PRODUCTION_REPO
          done
